#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# THE ROUND ZIP.
#
# 🔴 ROUND 153 — THIS EXISTS BECAUSE THE ARCHIVE LIVED IN A SHELL HISTORY.
# The exclusion list was retyped by hand every round, which is how
# `scripts/*.png` stayed in it for fifty rounds. Same reasoning as
# scripts/regression.txt in round 149: a list that matters belongs in the repo,
# not in whatever terminal happened to run it.
#
# 🔴 WHY THE SCREENSHOTS GO. Round 152's zip truncated in transfer three times
# — 1,991,151 / 1,293,427 / 1,462,549 bytes against 3,238,393. The eleven PNGs
# under scripts/ are 1.68 MB of that, FIFTY-TWO PER CENT of the archive, and
# they are the one part of it nobody has ever opened.
#
# ⚠️ AND THEY ARE WRITE-ONLY. Every one is a `page.screenshot({path})` output
# from a browser proof; grep finds them being WRITTEN by the proofs and read by
# nothing. They are regenerated whenever their proof runs, so excluding them
# loses nothing that cannot be remade in a minute — and they grow by one with
# every browser proof added, which is why this needed a permanent answer rather
# than a bigger transfer.
#
# ⚠️ THEY STAY IN THE REPOSITORY. Removing eleven committed files is a separate
# decision from leaving them out of a transfer, and it is not this script's to
# make. But nothing reads them, so `scripts/*.png` in .gitignore is the obvious
# next step if anyone wants the repo smaller too.
#
# Usage:  bash scripts/make-zip.sh 153
# ---------------------------------------------------------------------------
set -euo pipefail

ROUND="${1:?usage: make-zip.sh <round-number>}"
OUT="miracle-makers-round${ROUND}.zip"

cd "$(dirname "$0")/.."

rm -f "$OUT"
zip -rq "$OUT" . \
  -x 'node_modules/*' '*/node_modules/*' \
     '.next/*' '*/.next/*' \
     '.git/*' \
     '.vercel/*' \
     'test-results/*' \
     '*.zip' \
     'scripts/*.png' \
     '*.tsbuildinfo'
# ⚠️ `*.tsbuildinfo` IS A TSC CACHE, 151 KB of it, regenerated by the next
# `tsc --noEmit`. It was never meant to travel and it is not in .gitignore,
# which is the only reason it was being shipped at all.

# 🔴 A SIZE IS NOT AN INTEGRITY CHECK. Round 152 proved the archive was sound
# and the transfer was not, which took three round trips to establish. Print
# both so the next truncation is identified in one.
BYTES=$(stat -c %s "$OUT")
echo "$OUT"
echo "  bytes  $BYTES"
echo "  sha256 $(sha256sum "$OUT" | cut -d' ' -f1)"
echo "  files  $(unzip -l "$OUT" | tail -1 | awk '{print $2}')"
unzip -tq "$OUT" >/dev/null && echo "  integrity OK"
